### ISSUE TITLE
Fail to compile on version 4.0.0

### ISSUE THREAD

**Issue by FDrazicC4** [brewkit/components#101]
Created a new app from typescript template:
```sh
npx create-react-app my-app --template typescript
```
Followed steps from [Getting Started](https://brewkit.dev/components/?path=/docs/documentation-getting-started--page).

Ran `npm start`, and got Failed to compile error:

Failed to compile.

/home/filip/playground/my-app/node_modules/@brewkit/themes/cerveza/index.ts
TypeScript error in /home/filip/playground/my-app/node_modules/@brewkit/themes/cerveza/index.ts(2,33):
Could not find a declaration file for module 'lodash'. '/home/filip/playground/my-app/node_modules/lodash/lodash.js' implicitly has an 'any' type.
  Try `npm install @types/lodash` if it exists or add a new declaration (.d.ts) file containing `declare module 'lodash';`  TS7016

```
    1 | import { createMuiTheme } from '@material-ui/core/styles';
  > 2 | import { merge as _merge } from 'lodash';
      |                                 ^
    3 | import { color } from './variables';
    4 | 
    5 |
```

**Comment by lawren** [comment]
Are you still experiencing this issue?

**Comment by FDrazicC4** [comment]
> 
> 
> Are you still experiencing this issue?

No, cannot reproduce it anymore.  Closing the issue.
