### ISSUE TITLE
Dark Theme for Cerveza

### ISSUE THREAD

**Issue by emdrayallday** [brewkit/components#114]
Brewkit is now being used in the new Vite build, Need to add Dark Theme for the cerveza styles. Already seeing bugs being reported for the login page

![Screen Shot 2021-05-18 at 11 19 52 AM](https://user-images.githubusercontent.com/34116830/118678454-0a100c00-b7cb-11eb-9c3b-4b3229f1ea8d.png)

**Comment by lawren** [comment]
This has been added and is now available in the latest release.
